# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw/hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw || ORIG_REF_NAME==hw} -quiet] -quiet

# IP: bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_processing_system7_0_0 || ORIG_REF_NAME==hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_axi_gpio_0_0 || ORIG_REF_NAME==hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw/ip/hw_auto_pc_0/hw_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_auto_pc_0 || ORIG_REF_NAME==hw_auto_pc_0} -quiet] -quiet

# IP: bd/hw/ip/hw_ps7_0_axi_periph_0/hw_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw/ip/hw_rst_ps7_0_50M_0/hw_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hw_processing_system7_0_0 || ORIG_REF_NAME==hw_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hw_axi_gpio_0_0 || ORIG_REF_NAME==hw_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0_ooc.xdc

# XDC: bd/hw/ip/hw_axi_gpio_0_0/hw_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hw_axi_gpio_0_0 || ORIG_REF_NAME==hw_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hw/ip/hw_auto_pc_0/hw_auto_pc_0_ooc.xdc

# XDC: bd/hw/ip/hw_rst_ps7_0_50M_0/hw_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hw/ip/hw_rst_ps7_0_50M_0/hw_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hw/ip/hw_rst_ps7_0_50M_0/hw_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/hw/hw_ooc.xdc
